global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: ecommerce-dev
    env: local

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'spring-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'api-gateway'
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'user-service'
      - targets: ['host.docker.internal:8082']
        labels:
          service: 'product-service'
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'order-service'
      - targets: ['host.docker.internal:8084']
        labels:
          service: 'inventory-service'
      - targets: ['host.docker.internal:8085']
        labels:
          service: 'fulfillment-service'
      - targets: ['host.docker.internal:8086']
        labels:
          service: 'delivery-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
